AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB Table for MedAssureAI Artifacts - Single-table design with GSI'

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production
    Description: Environment name

  TableName:
    Type: String
    Default: MedAssureAI_Artifacts
    Description: Name of the DynamoDB table

  EnablePointInTimeRecovery:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable point-in-time recovery

Resources:
  MedAssureArtifactsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      
      # Primary Key Schema
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      
      # Global Secondary Index for reverse lookup
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      
      # Enable point-in-time recovery
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !Ref EnablePointInTimeRecovery
      
      # Enable encryption at rest
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      
      # Enable TTL for session cleanup
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      
      # Tags
      Tags:
        - Key: Name
          Value: MedAssureAI Artifacts Table
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: MedAssureAI
        - Key: ManagedBy
          Value: CloudFormation

  # CloudWatch Alarm for Read Throttle Events
  ReadThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${TableName}-read-throttle'
      AlarmDescription: Monitors DynamoDB read throttle events
      MetricName: ReadThrottleEvents
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: TableName
          Value: !Ref MedAssureArtifactsTable
      TreatMissingData: notBreaching

  # CloudWatch Alarm for Write Throttle Events
  WriteThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${TableName}-write-throttle'
      AlarmDescription: Monitors DynamoDB write throttle events
      MetricName: WriteThrottleEvents
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: TableName
          Value: !Ref MedAssureArtifactsTable
      TreatMissingData: notBreaching

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref MedAssureArtifactsTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'

  TableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt MedAssureArtifactsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TableArn'

  TableStreamArn:
    Description: Stream ARN of the DynamoDB table
    Value: !GetAtt MedAssureArtifactsTable.StreamArn
    Export:
      Name: !Sub '${AWS::StackName}-StreamArn'
